CREATE TABLE "MY_USERS" (
                            "ID"      NUMBER(38, 0) NOT NULL,
                            "NAME"    VARCHAR(255) NULL,
                            "AGE" NUMBER
);

ALTER TABLE "MY_USERS"
    ADD CONSTRAINT "PK_MY_USERS" PRIMARY KEY ("ID");
ALTER TABLE "MY_USERS"
    ADD CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP;
ALTER TABLE "MY_USERS"
    ADD UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP;

CREATE TABLE "MY_POSTS" (
                            "ID"      NUMBER(38, 0) NOT NULL,
                            "USER_ID" NUMBER(38, 0) NOT NULL,
                            "TITLE"    VARCHAR(255) NULL,
                            "CONTENT"  VARCHAR(255)
);

ALTER TABLE "MY_POSTS"
    ADD CONSTRAINT "PK_MY_POSTS" PRIMARY KEY ("ID");
ALTER TABLE "MY_POSTS"
    ADD CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP;
ALTER TABLE "MY_POSTS"
    ADD UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP;
